name: "🧪 Run VM test"

on:
  push:
    paths-ignore:
      - docker/**
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - docker/**

jobs:
  check:
    name: "🧪 Run VM test"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v5

      - name: "📦 Install Nix"
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: "🧪 Run Nextcloud App VM tests"
        run: nix build -L .#nixosTests.nextcloud-webapppassword
